name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main  # 兼容 main 分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须权限：允许 Action 推送代码到 gh-pages 分支

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build Book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages  # 这是生成的静态网页存放的分支
